# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  pagesLoadBuilder:
    import: "dev/builder.dart"
    builder_factories: ["pagesLoadBuilder"]
    build_extensions: {"@page.dart": [".dart.info.json"]}
    build_to: source
    auto_apply: root_package
#    defaults:
#      generate_for:
#        # Only apply to .dart files in the web directory
#        include:
#        - pages/**
    runs_before: ["flutter_note:pagesGenBuilder"]

  pagesGenBuilder:
#    import: "package:flutter_note/build_ext/builder.dart"
    import: "dev/builder.dart"
    builder_factories: ["pagesGenBuilder"]
    build_extensions: {"$package$": ["lib/generated/pages.g.dart"]}
    auto_apply: root_package
    build_to: source
