# ref:
#  https://github.com/dart-lang/build/tree/master/build_config
#  https://github.com/dart-lang/build/blob/master/docs/build_yaml_format.md
targets:
  $default:
    builders:
      flutter_note:pagesLoadBuilder:
        enabled: true
        generate_for:
          # Only apply to .dart files in the web directory
          include:
            - lib/pages/@page.dart
            - lib/pages/**/@page.dart
      flutter_note:pagesGenBuilder:
        enabled: true
      flutter_note:mateBuilder:
        enabled: true
        generate_for:
          # Only apply to .dart files in the web directory
          include:
            - lib/mate_hint.dart

builders:
  mateBuilder:
    import: "package:build_ext/builder.dart"
    builder_factories: ["mateBuilder"]
    #    build_extensions: {"^{{}}.dart": ["lib/generated/{{}}.dart"]}
    build_extensions: {".dart": [".dart.info.json"]}
    build_to: source
    auto_apply: root_package
  pagesLoadBuilder:
    import: "package:build_ext/builder.dart"
    builder_factories: ["pagesLoadBuilder"]
    build_extensions: {"@page.dart": [".no_output"]}
    build_to: cache # this builder no output
    auto_apply: none
    runs_before: ["flutter_note:pagesGenBuilder"]
  pagesGenBuilder:
    import: "package:build_ext/builder.dart"
    builder_factories: ["pagesGenBuilder"]
    build_extensions: {"$package$": ["lib/generated/pages.g.dart"]}
    auto_apply: none
    build_to: source