name: build_ext
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  build_runner_core: ^7.2.7
  package_config: ^2.1.0
  code_builder: ^4.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.0.0
  build: ^2.0.0
